
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.toIntExact;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LUCKY
 */
public class MainFrame extends javax.swing.JFrame {
    
    String nol_jam ="";
    String nol_menit="";
    String nol_detik="";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        selectData();
        setJam();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Struk = new javax.swing.JTextField();
        NoPol = new javax.swing.JTextField();
        Lama = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        Pinjam = new com.toedter.calendar.JDateChooser();
        Kembali = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        btSave = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        Jam = new javax.swing.JLabel();
        btHitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        btPrint1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));
        getContentPane().add(Struk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));
        getContentPane().add(NoPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, -1));

        Lama.setEditable(false);
        getContentPane().add(Lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, -1));

        Harga.setEditable(false);
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, -1));
        getContentPane().add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, -1));
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Harga");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama Peminjam");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Alamat Peminjam");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("No Struk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("No Polisi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Kembali");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Lama Hari");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 20));

        btClear.setText("CLEAR");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 110, 30));

        btPrint.setText("PRINT");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 110, 30));

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NoStruk", "NoPol", "Nama", "Alamat", "TanggalPinjam", "TanggalKembali", "Harga"
            }
        ));
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 560, 420));

        btSave.setText("SAVE");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 110, 30));

        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 110, 30));

        Jam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jam.setText("Jam");
        getContentPane().add(Jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        btHitung.setText("HITUNG");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("INPUT DATA PEMINJAM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        Tanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tanggal.setText("Tanggal");
        getContentPane().add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        btPrint1.setText("EXIT");
        btPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrint1ActionPerformed(evt);
            }
        });
        getContentPane().add(btPrint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 110, 30));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 480));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 590, 480));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Wednesday", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAFFA MOTORCYCLE RENTAL");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String kembali = dateFormat.format(Kembali.getDate());
        
        if(Alamat.getText().equals("") || Harga.getText().equals("") || pinjam.equals("") || kembali.equals("") || 
                Lama.getText().equals("") || Nama.getText().equals("") || NoPol.getText().equals("") || 
                Struk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data / Hitung terlebih dahulu !","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
           String SQL = "INSERT INTO tb_sewa VALUES('"+Struk.getText()+"','"+NoPol.getText()+"','"+Nama.getText()
                   +"','"+Alamat.getText()+"','"+pinjam+"','"+kembali+"','"+Harga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
        
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
           
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
       Date pinjam = Pinjam.getDate();
       Date kembali = Kembali.getDate();
       long startTime = pinjam.getTime();
       long endTime = kembali.getTime();
       long bedaTime = endTime - startTime;
       long bedaHari = bedaTime / (1000 * 60 * 60 * 24);
       DateFormat dateFormat = DateFormat.getDateInstance();
       
       Lama.setText(" "+bedaHari+" hari");
       
       int lama = toIntExact(bedaHari);
       int total = lama * 20000;
       String harga = Integer.toString(total);
       
       Harga.setText(harga);
    }//GEN-LAST:event_btHitungActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        Nama.setText("");
        Alamat.setText("");
        Struk.setText("");
        NoPol.setText("");
        Harga.setText("");
        Lama.setText("");
        Pinjam.setCalendar(null);
        Kembali.setCalendar(null);
    }//GEN-LAST:event_btClearActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        MessageFormat header = new MessageFormat("Data persewaan motor");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try
        {
            tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %a%n", e.getMessage());
        }
    }//GEN-LAST:event_btPrintActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int baris =  tbData.getSelectedRow();
        if (baris != -1)
        {
            String struk = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_sewa WHERE NoStruk='"+struk+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        int baris = tbData.getSelectedRow();
        if(baris != -1)
        {
            Struk.setText(tbData.getValueAt(baris, 0).toString());
            NoPol.setText(tbData.getValueAt(baris, 1).toString());
            Nama.setText(tbData.getValueAt(baris, 2).toString());
            Alamat.setText(tbData.getValueAt(baris, 3).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try 
            {
                dateFormat = date.parse(tbData.getValueAt(baris, 4).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Pinjam.setDate(dateFormat);
            
            try 
            {
                dateFormat = date.parse(tbData.getValueAt(baris, 5).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Kembali.setDate(dateFormat);
            Harga.setText(tbData.getValueAt(baris, 6).toString());
            
            int hari = Integer.parseInt(tbData.getValueAt(baris, 6).toString()) / 20000;
            Lama.setText(" "+hari+" hari" );
        }
    }//GEN-LAST:event_tbDataMouseClicked

    private void btPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrint1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btPrint1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Harga;
    private javax.swing.JLabel Jam;
    private com.toedter.calendar.JDateChooser Kembali;
    private javax.swing.JTextField Lama;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField NoPol;
    private com.toedter.calendar.JDateChooser Pinjam;
    private javax.swing.JTextField Struk;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btPrint1;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbData;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NoStruk","NoPol","Nama","Alamat","TanggalPinjam","TanggalKembali","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM `tb_sewa`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next())
            {
                
                String NoStruk = rs.getString(1);
                String NoPol = rs.getString(2);
                String Nama = rs.getString(3);
                String Alamat = rs.getString(4);
                String TanggalPinjam = rs.getString(5);
                String TanggalKembali = rs.getString(6);
                String Harga = rs.getString(7);
                String data[] = {NoStruk,NoPol,Nama,Alamat,TanggalPinjam,TanggalKembali,Harga};
                dtm.addRow(data);
                        
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        tbData.setModel(dtm);
    }

    private void setJam() 
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if (nilai_jam <= 9)
                {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9)
                {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9)
                {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Jam.setText("Jam "+jam +":"+ menit + ":"+ detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }

    private void setTanggal() 
    {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Tanggal.setText(kal.format(now));
    }
}

